# Generated by Django 5.0.3 on 2024-08-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/reviews'),
        ),
    ]
