# Generated by Django 5.0.3 on 2024-08-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productreview_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='ordered_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
    ]
