# Generated by Django 5.0.3 on 2024-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productvariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='name',
            field=models.CharField(blank=True, choices=[("O'lchami", "O'lchami"), ('Rangi', 'Rangi'), ('Hajmi', 'Hajmi'), ('Xotirasi', 'Xotirasi'), ("Og'irligi", "Og'irligi")], max_length=255, null=True),
        ),
    ]
