# Generated by Django 5.0.3 on 2024-08-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_price_product_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
