# Generated by Django 5.0.3 on 2024-05-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JWTToken',
        ),
    ]
