# Generated by Django 5.0.3 on 2024-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_user_alter_orderitems_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
