# Generated by Django 5.0.3 on 2024-07-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitems_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
