# Generated by Django 5.0.3 on 2024-07-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
