# Generated by Django 5.0.3 on 2024-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[('Kutilmoqda...', 'Kutilmoqda...'), ("Jo'natilinmoqda...", "Jo'natilinmoqda..."), ('Yetkazib berildi', 'Yetkazib berildi'), ('Bekor qilindi', 'Bekor qilindi')], default='Kutilmoqda...', max_length=50),
        ),
    ]
