# Generated by Django 5.0.3 on 2024-08-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='smtp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda...'), ("Jo'natilinmoqda", "Jo'natilinmoqda..."), ('Yetkazib berildi', 'Yetkazib berildi'), ('Bekor qilindi', 'Bekor qilindi')], default='Kutilmoqda', max_length=50),
        ),
    ]
