# Generated by Django 5.0.3 on 2024-08-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_smtp_code_alter_orderitems_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'created_at'},
        ),
    ]
